// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJS-HgfmqkgsLQmfHvaHFbYoH4vGVIwec',
    appId: '1:964679237913:web:bdadf44ecfe8a19b25c588',
    messagingSenderId: '964679237913',
    projectId: 'explore-ci-cd-d7b17',
    authDomain: 'explore-ci-cd-d7b17.firebaseapp.com',
    storageBucket: 'explore-ci-cd-d7b17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApUY-kNWH-A6sk6GBh9WbEvExbJdVYoc',
    appId: '1:964679237913:android:22dbe9126c2a84aa25c588',
    messagingSenderId: '964679237913',
    projectId: 'explore-ci-cd-d7b17',
    storageBucket: 'explore-ci-cd-d7b17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeM3BmmaF0KeE1cJH0YKZYyzNeLEk6N14',
    appId: '1:964679237913:ios:77ebdebcc2c3709025c588',
    messagingSenderId: '964679237913',
    projectId: 'explore-ci-cd-d7b17',
    storageBucket: 'explore-ci-cd-d7b17.firebasestorage.app',
    iosBundleId: 'com.example.exploreCiCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeM3BmmaF0KeE1cJH0YKZYyzNeLEk6N14',
    appId: '1:964679237913:ios:77ebdebcc2c3709025c588',
    messagingSenderId: '964679237913',
    projectId: 'explore-ci-cd-d7b17',
    storageBucket: 'explore-ci-cd-d7b17.firebasestorage.app',
    iosBundleId: 'com.example.exploreCiCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJS-HgfmqkgsLQmfHvaHFbYoH4vGVIwec',
    appId: '1:964679237913:web:75c67b418541afb825c588',
    messagingSenderId: '964679237913',
    projectId: 'explore-ci-cd-d7b17',
    authDomain: 'explore-ci-cd-d7b17.firebaseapp.com',
    storageBucket: 'explore-ci-cd-d7b17.firebasestorage.app',
  );
}
