name: Flutter CI/CD - Android Build & Firebase Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          # 3.x # Change to your Flutter version

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\Pub\Cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # - name: Install dependencies
      #   run: flutter pub get

      - name: Decode Firebase Service Account Key
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $env:GITHUB_WORKSPACE\service-account.json
        shell: pwsh

      - name: Authenticate Firebase
        run: |
          set GOOGLE_APPLICATION_CREDENTIALS=$env:GITHUB_WORKSPACE\service-account.json

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk ^
            --app "${{ secrets.FIREBASE_APP_ID }}" ^
            --token "${{ secrets.FIREBASE_CI_TOKEN }}" ^
            --groups testers ^
            --release-notes "Testing the app"
