name: Flutter CI/CD - Android Build & Firebase Distribution

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0" # Match your local version
          channel: "stable"
          cache: true

      - name: Verify Flutter & Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\Pub\Cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Firebase Service Account Key
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $env:GITHUB_WORKSPACE\service-account.json
        shell: pwsh

      # - name: Authenticate Firebase
      #   run: |
      #     set GOOGLE_APPLICATION_CREDENTIALS=$env:GITHUB_WORKSPACE\service-account.json

      - name: Authenticate Firebase
        run: |
          gci
          npx firebase-tools login:ci --token "$(cat $env:GITHUB_WORKSPACE\service-account.json)" || echo "Skipping login"
          export GOOGLE_APPLICATION_CREDENTIALS="$env:GITHUB_WORKSPACE\service-account.json"
        shell: bash

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk ^
            --app "${{ secrets.FIREBASE_APP_ID }}" ^
            --token "${{ secrets.FIREBASE_CI_TOKEN }}" ^
            --groups testers ^
            --release-notes "Testing the app"
        shell:
          cmd

          # firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk ^
          #   --app "${{ secrets.FIREBASE_APP_ID }}" ^
          #   --token "${{ secrets.FIREBASE_CI_TOKEN }}" ^
          #   --groups testers ^
          #   --release-notes "Testing the app"
